[book]
authors = ["dxo"]
language = "en"
multilingual = false
src = "src"
title = "The Act Book"

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"
[preprocessor.katex]
after = ["links"]

[output]
[output.html]
additional-js =["mermaid.min.js", "mermaid-init.js"]
