name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        # we need this to map platform names as used by github to
        # the attribute names defined in release.nix
        include:
          - os: ubuntu-latest
            os_attr: linux
          - os: macos-latest
            os_attr: darwin
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v22
        with:
          skip_adding_nixpkgs_channel: false
      - uses: cachix/cachix-action@v12
        with:
          name: dapp
          skipPush: true
          signingKey: ''
      - name: test
        run: nix develop --ignore-environment --command bash -c "cabal update && make test-ci"
      - name: build
        run: nix build .#act
