name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        # we need this to map platform names as used by github to
        # the attribute names defined in release.nix
        include:
          - os: ubuntu-latest
            os_attr: linux
          - os: macos-latest
            os_attr: darwin
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@ef6c38c42ba153b4be4b764b71c87c1610896378 # v15
        with:
          skip_adding_nixpkgs_channel: false
      - uses: cachix/cachix-action@3db1a09d3a573d7b62801116405ad5aa0f59c904 # v10
        with:
          name: dapp
          skipPush: true
          signingKey: ''
      - name: test
        run: nix-shell --pure --command "cabal new-update && make test"
      - name: build
        run: nix-build -A act

